# Global Settings
platform=ios

# Android Specifics
android.device.name=Pixel 9
android.platform.version=16.0
android.app.path=src/test/resources/apps/qa-test-app.apk

# iOS Specifics
ios.device.name=iPhone 17
ios.platform.version=26.1
ios.app.path=src/test/resources/apps/qa-test-app.app